title: ManyMusic-Acq
description: Progress documentation for ManyMusic-fMRI+ acquisition
version: 0.0.2
baseurl: manymusic.net
language: en
theme: just-the-docs
color_scheme: light
math: katex
url: https://manymusic.net/acq/
aux_links:
  project-home: https://manymusic.net/
ga_tracking: "G-TJWXHKQYN9"
ga_tracking_anonymize_ip: true